#!/bin/sh


sleeptime=5
code_file=/tmp/up_code

STAGE_INIT=0
STAGE_DOWNLOAD=2

ERR_NONE=0
ERR_ANOTHER_RUNNING=1
ERR_DOWNLOAD_FAILED=2


echo "$STAGE_DOWNLOAD $ERR_NONE $$" >$code_file
AUTO_UPGRADE_LOCK=/tmp/auto_upgrade_lock

if [[ -e "$AUTO_UPGRADE_LOCK" ]];then
	echo "$STAGE_DOWNLOAD $ERR_ANOTHER_RUNNING $$" >$code_file
	sleep $sleeptime
	echo "$STAGE_INIT $ERR_NONE $$" >$code_file
	exit
else
	touch $AUTO_UPGRADE_LOCK
fi

file=/tmp/upgrade.bin

url=`uci get onekeyupgrade.config.newurl`
size=`uci get onekeyupgrade.config.Size`

wget -T 30 -t 5 -O $file $url

if [ -e "$file" ];then # 有文件下载下来

	filesize=`ls -l $file | awk '{print $5}'`

	if [[ "$filesize" != "$size" ]];then
		echo "$STAGE_DOWNLOAD $ERR_DOWNLOAD_FAILED $$" >$code_file
		sleep $sleeptime
		echo "$STAGE_INIT $ERR_NONE $$" >$code_file
		rm $AUTO_UPGRADE_LOCK
		rm $file
		exit
	else
		/usr/sbin/manual_upgrade -u $file
		ret=$?
		rm $AUTO_UPGRADE_LOCK
		return $ret
	fi
else
	echo "$STAGE_DOWNLOAD $ERR_DOWNLOAD_FAILED $$" >$code_file
	sleep $sleeptime
	echo "$STAGE_INIT $ERR_NONE $$" >$code_file
	rm $AUTO_UPGRADE_LOCK
	exit
fi
