#!/bin/sh

sleeptime=5
code_file=/tmp/up_code

STAGE_INIT=0
STAGE_GET_INFO=1

ERR_NONE=0
ERR_ALREADY_UP_TO_DATE=1
ERR_NETWORK_ANOMALY=2

echo "$STAGE_GET_INFO $ERR_NONE $$" >$code_file

ubus call http check_upgrade

retState=`uci get onekeyupgrade.config.retState`
if [ "$retState" == "1" ] ; then
	ErrorCode=`uci get onekeyupgrade.config.ErrorCode`
	if [ "$ErrorCode" == "0" ] ; then
		VerNum=`uci get onekeyupgrade.config.VerNum`
		if [ "$VerNum" == "1" ] ; then
			do_upgrade
			exit
		else
			echo "$STAGE_GET_INFO $ERR_ALREADY_UP_TO_DATE $$" > $code_file #当前已是最新版本
			sleep $sleeptime
			echo "$STAGE_GET_INFO $ERR_NONE $$" >$code_file
		fi
	else
		echo "$STAGE_GET_INFO $ERR_NETWORK_ANOMALY $$" > $code_file #服务器通信失败
		sleep $sleeptime
		echo "$STAGE_GET_INFO $ERR_NONE $$" >$code_file
	fi
else
	echo "$STAGE_GET_INFO $ERR_NETWORK_ANOMALY $$" > $code_file #服务器通信失败
	sleep $sleeptime
	echo "$STAGE_GET_INFO $ERR_NONE $$" >$code_file
fi

sleep $sleeptime

echo "$STAGE_INIT $ERR_NONE $$" > $code_file

exit
