#!/bin/sh /etc/rc.common

START=60
USE_PROCD=1

start_service() {
    mknod /dev/gpio c 252 0
	procd_open_instance
	procd_set_param command /usr/bin/button i
	procd_set_param respawn
	procd_close_instance

	procd_open_instance
	procd_set_param command /usr/bin/button l
	procd_set_param respawn
	procd_close_instance


}
