#!/bin/sh /etc/rc.common

START=99
STOP=20
USE_PROCD=1

start_service()
{
    flag_reboot=`uci get collect.main.reboot_flag 2>/dev/null`
    if [ -n "$flag_reboot" ];then
        if [ "$flag_reboot" = "1" ];then
            uci set collect.main.reboot_flag=0
            uci commit collect
        else
            uci set collect.main.report_flag=1
            uci commit collect
            statistics power &
        fi
    else
        uci set collect.main.report_flag=1
        uci set collect.main.reboot_flag=0
        uci commit collect
        statistics power &
    fi

    procd_open_instance
    procd_set_param command /usr/bin/collect
    procd_set_param respawn
    procd_close_instance
}

stop_service()
{
    uci set collect.main.reboot_flag=1
    uci set collect.main.report_flag=1
    uci commit collect
}
