#!/bin/sh /etc/rc.common
# Copyright (C) 2014 OpenWrt.org

START=97

start() {
	lan_ip=`ifconfig br-lan |grep addr:|cut -f2 -d":"|cut -f1 -d" "`
	/usr/sbin/iptables -t filter -w -F guest_chain >/dev/null 2>&1
	/usr/sbin/iptables -t filter -w -D INPUT -j guest_chain >/dev/null 2>&1
	/usr/sbin/iptables -t filter -w -X guest_chain >/dev/null 2>&1

	/usr/sbin/iptables -t filter -w -N guest_chain >/dev/null 2>&1
	/usr/sbin/iptables -t filter -w -I INPUT -j guest_chain >/dev/null 2>&1
	/usr/sbin/iptables -t filter -w -A guest_chain -m indev --indev-name rax1 -d $lan_ip/24 -p tcp --dport 80 -j DROP >/dev/null 2>&1
}

stop() {
	/usr/sbin/iptables -t filter -w -F guest_chain >/dev/null 2>&1
	/usr/sbin/iptables -t filter -w -D INPUT -j guest_chain >/dev/null 2>&1
	/usr/sbin/iptables -t filter -w -X guest_chain >/dev/null 2>&1
}
