#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

DEFAULT=/etc/default/pppoe-server

start() {
	guide=`uci get luci.main.guide`
	if [ "$guide"x = "1"x ]; then
		[ -f $DEFAULT ] && . $DEFAULT
		service_start /usr/sbin/pppoe-server $OPTIONS
	fi
}

stop() {
	service_stop /usr/sbin/pppoe-server
}
