#!/bin/sh /etc/rc.common

######################################################################
#
# Function  : init script, telnetd_startup
#
# Creater   : xiangda.zhang@feixun.com.cn, 2016-05-04
#
# Copyright : Shanghai Phicomm
#
######################################################################

START=80

boot() {
  /usr/bin/telnetd_startup &
}

start() {
  /usr/bin/telnetd_startup &
}

stop() {
  killall -9 telnetd_startup
}

restart() {
  stop
  start
}
