#!/bin/sh

local file="/tmp/adpush/portal.html"

modify_adpush() {
	local lanip=$(uci -P /var/state get network.lan.ipaddr)
	[ -z "$lanip" ] && return
	
	sed -i 's/http:\/\/.*:8082/http:\/\/'$lanip':8082/' $file
	sed -i 's/http:\/\/.*\/adpush/http:\/\/'$lanip'\/adpush/' $file
	
	[ -n "`iptables -t nat -S PREROUTING | grep '\-j REDIRECT \-\-to\-ports 8082'`" ] && {
		adportal 0
		sleep 1
		adportal 1
	}
}

[ "$ACTION" = "ifup" -a "$INTERFACE" = "lan" ] && {
	[ -f $file ] && modify_adpush
}

