#!/bin/sh 
. /lib/functions/nvram2uci.sh

wps_2g_enable=`nvram get linux  WscModeOption`
wps_5g_enable=`nvram get linux  inic_WscModeOption`

if [ $wps_2g_enable = "7" -a $wps_5g_enable = "7" ];then
	enabled="1"
else
	enabled="0"

fi
uci set wps_config.wps_para.wps_enable=$enabled
uci commit

nvram2uci WscVendorPinCode wps_config.wps_para.pincode_2g
nvram2uci inic_WscVendorPinCode wps_config.wps_para.pincode_5g
