#!/bin/sh

. /lib/functions.sh

append_aff_list() {
	export "aff_list=$aff_list $1"
}

resolve_affects() {
	local aff_list

	config_list_foreach $1 affects append_aff_list

	export "deps=$deps $aff_list"
}

resolve_deps() {
	local name=$1
	local reload=$name
	local deps=
	local tmplist=
	config_foreach resolve_affects $name
	
	for dep in $deps; do
		tmplist=$(resolve_deps $dep)
		for tmp in $tmplist; do
			reload="$reload $tmp"
		done
	done

	echo $reload
}

config_load ucitrack
CONFIG_LIST=
for fname in $@;do
	reload_list=$(resolve_deps $fname)
	for reload_item in $reload_list;do
		if list_contains CONFIG_LIST $reload_item;then
			:
		else
			CONFIG_LIST="$CONFIG_LIST $reload_item"
		fi
	done
done

/sbin/luci-reload $CONFIG_LIST

