#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

failsafe_netlogin () {
	telnetd -l /bin/login.sh <> /dev/null 2>&1
}

failsafe_shell() {
	lock /tmp/.failsafe
	ash --login
	echo "Please reboot system when done with failsafe network logins"
}

failsafe_wireless() {
	case `cat /proc/cpuinfo | grep MT76` in
		*7621*)
			CONFIG_RALINK_MT7621=y
			;;
		*7620*)
			CONFIG_RALINK_MT7620=y
			;;
	esac

	if [ "$CONFIG_RALINK_MT7621" = "y" ]; then
		ifconfig ra0 up
		ifconfig rax0 up
	fi

	echo "load wireless module"
}

boot_hook_add failsafe failsafe_netlogin
boot_hook_add failsafe failsafe_wireless
boot_hook_add failsafe failsafe_shell

